name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: make test
    - name: Check style
      run: make style
    - name: Compile release binary
      run: make release
    - uses: actions/upload-artifact@v4.6.2
      with:
        name: mhrs
        path: target/release/mhrs
